# Generated by Django 5.2.4 on 2025-10-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_userprofile_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
