# Generated by Django 5.2.4 on 2025-12-17 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='Original disfluent speech text')),
                ('preprocessed_text', models.TextField(help_text='Text after pattern-based preprocessing')),
                ('corrected_text', models.TextField(help_text='Final fluent corrected text')),
                ('language', models.CharField(default='en', help_text='Language code (en, hi, ml, es)', max_length=10)),
                ('gender', models.CharField(default='female', help_text='Voice gender', max_length=10)),
                ('has_corrections', models.BooleanField(default=False, help_text='Whether disfluencies were found and corrected')),
                ('original_word_count', models.IntegerField(default=0)),
                ('corrected_word_count', models.IntegerField(default=0)),
                ('disfluencies_removed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speech History',
                'verbose_name_plural': 'Speech Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
